
rm ./logger/BUILD &&
rm ./node/BUILD &&
rm ./record/BUILD &&
rm ./scheduler/BUILD &&
rm ./data/BUILD &&
rm ./sysmo/BUILD &&
rm ./proto/BUILD &&
rm ./timer/BUILD &&
rm ./py_wrapper/BUILD &&
rm ./service_discovery/BUILD &&
rm ./common/BUILD &&
rm ./examples/common_component_example/BUILD &&
rm ./examples/proto/BUILD &&
rm ./examples/timer_component_example/BUILD &&
rm ./examples/BUILD &&
rm ./croutine/BUILD &&
rm ./class_loader/BUILD &&
rm ./class_loader/test/BUILD &&
rm ./tools/cyber_recorder/BUILD &&
rm ./tools/cyber_monitor/BUILD &&
rm ./python/cyber_py/examples/BUILD &&
rm ./time/BUILD &&
rm ./message/BUILD &&
rm ./service/BUILD &&
rm ./transport/BUILD &&
rm ./blocker/BUILD &&
rm ./parameter/BUILD &&
rm ./task/BUILD &&
rm ./component/BUILD &&
rm ./event/BUILD &&
rm ./io/BUILD